version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fortunecloud-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - fortunecloud-network
    restart: unless-stopped

networks:
  fortunecloud-network:
    driver: bridge
